services:
  postgres:
    image: postgres:15
    container_name: bjj-feedback-db
    restart: always
    environment:
      POSTGRES_USER: bjjuser
      POSTGRES_PASSWORD: bjjfeedback
      POSTGRES_DB: bjjfeedback
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
