services:
  postgres:
    image: postgres:15
    container_name: restaurant-app-db
    environment:
      POSTGRES_DB: restaurantdb
      POSTGRES_USER: restaurantuser
      POSTGRES_PASSWORD: restaurantpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
